<?php
$this->headTitle('Levels');
$this->mainMenu()->setActiveItemId('consultants');
$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('consultants.manage') => $this->url('beheer/consultants'),
]);
?>
<h1><?php echo $this->translator()->translate('manage.consultants'); ?></h1>
<p>
    <a class="btn btn-dark" href="
       <?= $this->url('beheer/consultants', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translator()->translate('new.consultant'); ?>
    </a>
</p>
<table class="table table-bordered table-striped table-sm tablesorter">
    <thead class="thead-light">
        <tr>
            <th><?php echo $this->translator()->translate('table.consultants.name'); ?></th>
            <th><?php echo $this->translator()->translate('table.consultants.date.created'); ?></th>
            <th class="text-center sorter-false"><i class="fas fa-cogs"></i></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
            <tr>
                <td>
                    <?= $this->escapeHtml($item->getFullName()); ?>
                </td>
                <td>
                    <?php echo $item->getCreatedAt()->format('d-m-Y H:m:s'); ?>
                </td>
                <td class="text-center">
                    <a class="btn btn-dark btn-sm" href="<?= $this->url('beheer/consultants', ['action' => 'edit', 'id' => $item->getId()]); ?>">
                                        <i class="fas fa-edit"></i>
                                    </a>
                    <a class="btn btn-danger btn-sm" href="<?= $this->url('beheer/consultants', ['action' => 'delete', 'id' => $item->getId()]); ?>">
                                        <i class="fas fa-trash"></i>
                                    </a>
                </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>