<div class="row mt-2">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table class="table table-bordered table-condensed" id="contactsTable">
            <thead class="thead-dark">
                <tr>
                    <th colspan="4">Contacts</th>
                    <th class="text-right"><button type="button" class="btn btn-light btn-sm" data-toggle="modal" data-target=".bd-example-modal-lg"><i class="fas fa-plus-square"></i></button></th>
                </tr>
                <tr>
                    <th>Surname</th>
                    <th>Lastname prefix</th>
                    <th>Lastname</th>
                    <th>Gender</th>
                    <th class="text-center"><i class="fas fa-cogs"></i></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($contacts AS $contact) { ?>
                    <tr>
                        <td><?php echo $contact->getSurname(); ?></td>
                        <td><?php echo $contact->getLastNamePrefix(); ?></td>
                        <td><?php echo $contact->getLastname(); ?></td>
                        <td>
                            <?php
                            echo ($contact->getGender() == 1 ? '<i class="fas fa-male"></i>' : '');
                            echo ($contact->getGender() == 2 ? '<i class="fas fa-female"></i>' : '');
                            echo ($contact->getGender() == 3 ? '<i class="fas fa-genderless"></i>' : '');
                            ?>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-dark btn-sm" href="<?= $this->url('beheer/contacts', ['action' => 'edit', 'id' => $contact->getId()]); ?>">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a class="btn btn-danger btn-sm" href="<?= $this->url('beheer/contacts', ['action' => 'delete', 'id' => $contact->getId()]); ?>">
                                <i class="fas fa-trash"></i>
                            </a>
                            <a class="btn btn-dark btn-sm" href="<?= $this->url('beheer/contacts', ['action' => 'show', 'id' => $contact->getId()]); ?>">
                                <i class="fas fa-search-plus"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Contacts modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="contactModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add contact</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <?php echo $this->form()->openTag($form); ?>
            <div class="modal-body">
                <?php echo $this->partial('customers/contact/partials/form.phtml', array('form' => $form)); ?>
            </div>
            <div class="modal-footer">
                <button type="submit" id="addContact" class="btn btn-dark">Add</button> 
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
</div>