<div class="row mt-2">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table class="table table-bordered table-condensed" id="contactsTable">
            <thead class="thead-dark">
                <tr>
                    <th colspan="4">Contacts</th>
                    <th class="text-right"><button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".bd-example-modal-lg"><i class="fas fa-plus-square"></i></button></th>
                </tr>
                <tr>
                    <th>Surname</th>
                    <th>Lastname prefix</th>
                    <th>Lastname</th>
                    <th>Gender</th>
                    <th class="text-center"><i class="fas fa-cogs"></i></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($contacts AS $contact) { ?>
                    <tr>
                        <td><?php echo $contact->getSurname(); ?></td>
                        <td><?php echo $contact->getLastNamePrefix(); ?></td>
                        <td><?php echo $contact->getLastname(); ?></td>
                        <td>
                            <?php
                            echo ($contact->getGender() == 1 ? '<i class="fas fa-male"></i>' : '');
                            echo ($contact->getGender() == 2 ? '<i class="fas fa-female"></i>' : '');
                            echo ($contact->getGender() == 3 ? '<i class="fas fa-genderless"></i>' : '');
                            ?>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-primary btn-sm" href="<?= $this->url('beheer/contacts', ['action' => 'edit', 'id' => $contact->getId()]); ?>">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a class="btn btn-primary btn-sm" href="<?= $this->url('beheer/contacts', ['action' => 'delete', 'id' => $contact->getId()]); ?>">
                                <i class="fas fa-trash"></i>
                            </a>
                            <a class="btn btn-primary btn-sm" href="<?= $this->url('beheer/contacts', ['action' => 'show', 'id' => $contact->getId()]); ?>">
                                <i class="fas fa-search-plus"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Contacts modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="contactModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add contact</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formHidden($form->get('customer')); ?>

            <div class="modal-body">
                <div class="form-group row">
                    <?php echo $this->formLabel($form->get('surName')); ?>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <?php echo $this->formText($form->get('surName')); ?>
                    </div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <?php echo (count($form->getMessages('surName')) > 0 ? $form->getMessages('surName')['isEmpty'] : '&nbsp;' ) ?>
                    </div>
                </div>
                <div class="form-group row">
                    <?php echo $this->formLabel($form->get('lastName')); ?>
                    <div class="col-sm-4 col-md-4 col-lg-4">
                        <?php echo $this->formText($form->get('lastName')); ?>
                    </div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <?php echo $this->formText($form->get('lastNamePrefix')); ?>
                    </div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <?php echo (count($form->getMessages('lastName')) > 0 ? $form->getMessages('lastName')['isEmpty'] : '&nbsp;' ) ?>
                        <?php echo (count($form->getMessages('lastNamePrefix')) > 0 ? $form->getMessages('lastNamePrefix')['isEmpty'] : '&nbsp;' ) ?>
                    </div>
                </div>
                <div class="form-group row">
                    <?php echo $this->formLabel($form->get('gender')); ?>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <?php echo $this->formRadio($form->get('gender')); ?>
                    </div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <?php echo (count($form->getMessages('gender')) > 0 ? $form->getMessages('gender')['isEmpty'] : '&nbsp;' ) ?>
                    </div>
                </div>
                <div class="form-group row">
                    <?php echo $this->formLabel($form->get('phoneNumber')); ?>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <?php echo $this->formText($form->get('phoneNumber')); ?>
                    </div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <?php echo (count($form->getMessages('phoneNumber')) > 0 ? $form->getMessages('phoneNumber')['isEmpty'] : '&nbsp;' ) ?>
                    </div>
                </div>
                <div class="form-group row">
                    <?php echo $this->formLabel($form->get('mobilePhoneNumber')); ?>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <?php echo $this->formText($form->get('mobilePhoneNumber')); ?>
                    </div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <?php echo (count($form->getMessages('mobilePhoneNumber')) > 0 ? $form->getMessages('mobilePhoneNumber')['isEmpty'] : '&nbsp;' ) ?>
                    </div>
                </div>
                <div class="form-group row">
                    <?php echo $this->formLabel($form->get('email')); ?>
                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <?php echo $this->formText($form->get('email')); ?>
                    </div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <?php echo (count($form->getMessages('email')) > 0 ? $form->getMessages('email')['isEmpty'] : '&nbsp;' ) ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" id="addContact" class="btn btn-success">Add</button> 
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
</div>