<?php
$this->headTitle('Countries');

$this->mainMenu()->setActiveItemId('countries');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Countries' => $this->url('beheer/countries'),
    'Edit Country' => $this->url('beheer/countries', ['action' => 'edit'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<h1>Manage Countries</h1>
<?php echo $this->form()->openTag($form); ?>
<?php
//Country form
echo $this->partial('customers/country/partials/form.phtml', array('form' => $form, 'country' => $country));
?>
<!-- Image upload -->
<?php echo $this->partial('upload-images/partial/show_image.phtml', array('formImage' => $formImage, 'image' => $image, 'returnURL' => $returnURL)); ?>
<!-- End image upload -->
<div class="form-group row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="submit" id="submit" class="btn btn-dark">Save</button> 
        <a href="<?php echo $this->url('beheer/countries') ?>" class="btn btn-danger" title="Annuleren">Cancel</a>
    </div>  
</div>
<?php echo $this->form()->closeTag($form); ?>