<?php
$this->headTitle('Countries');

$this->mainMenu()->setActiveItemId('countries');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Countries' => $this->url('beheer/countries'),
]);
?>

<h1>Manage Countries</h1>

<p>
    <a class="btn btn-dark" href="
       <?= $this->url('beheer/countries', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Country
    </a>
</p>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Name</th>
            <th>Date Created</th>
            <th></th>
        </tr>
    </thead>
    <?php foreach ($countries as $country): ?>
        <tr>
            <td>
                <?= $this->escapeHtml($country->getName()); ?></a> 
            </td>
            <td>
                <?= (is_object($country->getDateCreated()) ? $this->escapeHtml($country->getDateCreated()->format('Y-m-d')) : ''); ?>
            </td>        
            <td>
                <a class="btn btn-dark" href="<?= $this->url('beheer/countries', ['action' => 'edit', 'id' => $country->getId()]); ?>">
                    <i class="fas fa-edit"></i>
                </a>
                <a class="btn btn-danger" href="<?= $this->url('beheer/countries', ['action' => 'delete', 'id' => $country->getId()]); ?>">
                    <i class="fas fa-trash"></i>
                </a>
            </td>    
        </tr>
    <?php endforeach; ?>   
</table>
