<?php
$this->headTitle('Customers');

$this->mainMenu()->setActiveItemId('customer');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    $this->translator()->translate('projects.manage') => $this->url('beheer/customers'),
]);
?>

<h1><?php echo $this->translator()->translate('projects.manage'); ?></h1>

<p>
    <a class="btn btn-primary" href="
       <?= $this->url('beheer/projects', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translator()->translate('new.project'); ?>
    </a>
    <a class="btn btn-primary" href="
       <?= $this->url('beheer/projecttypes', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translator()->translate('new.projec.type'); ?>
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th><?php echo $this->translator()->translate('table.projects.name'); ?></th>
        <th><?php echo $this->translator()->translate('table.projects.date.created'); ?></th>
    </tr>

    <?php foreach ($projectTypes as $projectType): ?>

        <tr>
            <td>
                <?= $this->escapeHtml($projectType->getName()); ?></a> 
            </td>
            <td><nobr><?= (is_object($projectType->getDateCreated()) ? $this->escapeHtml($projectType->getDateCreated()->format('Y-m-d')) : ''); ?></nobr></td>        
    <td>
        <a class="btn btn-info" href="<?= $this->url('beheer/projecttypes', ['action' => 'edit', 'id' => $projectType->getId()]);
            ?>">
            <span class="glyphicon glyphicon-pencil" ></span> <?php echo $this->translator()->translate('edit'); ?>
        </a>
    </td>    
    </tr>

<?php endforeach; ?>   

</table>
