<?php
$this->headTitle('Customers');

$this->mainMenu()->setActiveItemId('customer');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Customers' => $this->url('beheer/customers'),
    'Show Customer' => $this->url('beheer/customers', ['action' => 'show'])
]);
?>
<h1><?php echo $customer->getName(); ?><span class="text-right"><?php echo '<img class="img-responsive" src="/' . $customer->getCountry()->getCountryImage()->getImageTypes('450x300')[0]->getFolder() . $customer->getCountry()->getCountryImage()->getImageTypes('450x300')[0]->getFileName() . '?v=' . rand() . '" alt="' . $customer->getCountry()->getCountryImage()->getAlt() . '" width="25" height="auto" />'; ?></span></h1>
<div class="row">
    <label class="col-sm-3 col-md-3 col-lg-3">Street</label>
    <div class="col-sm-3 col-md-3 col-lg-3">
        <?php echo $customer->getVisitStreet(); ?>
    </div>
    <label class="col-sm-3 col-md-3 col-lg-3">Number</label>
    <div class="col-sm-3 col-md-3 col-lg-3">
        <?php echo $customer->getVisitNumber(); ?>
    </div>
</div>
<div class="row">
    <label class="col-sm-3 col-md-3 col-lg-3">Postalcode</label>
    <div class="col-sm-3 col-md-3 col-lg-3">
        <?php echo $customer->getVisitPostalCode(); ?>
    </div>
    <label class="col-sm-3 col-md-3 col-lg-3">City</label>
    <div class="col-sm-3 col-md-3 col-lg-3">
        <?php echo $customer->getVisitCity(); ?>
    </div>
</div>
<?php
//Contact form
echo $this->partial('customers/customer/partials/contact-form.phtml', array('form' => $form, 'contacts' => $contacts));
?>
