<?php
$this->headTitle('Customers');

$this->mainMenu()->setActiveItemId('customers');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Customers' => $this->url('beheer/customers'),
    'Edit Contact' => $this->url('beheer/customers', ['action' => 'show', 'id' => $customer->getId()])
]);
$form->setAttributes(array(
    'enctype' => 'multipart/form-data'
));
?>
<h1>Manage Contact</h1>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->partial('customers/contact/partials/form.phtml', array('form' => $form)); ?>
<!-- Image upload -->
<?php echo $this->partial('customers/contact/partials/show_image.phtml', array('formImage' => $formImage, 'image' => $image, 'returnURL' => $returnURL)); ?>
<!-- End image upload -->
<div class="form-group row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="submit" id="submit" class="btn btn-success">Opslaan</button> 
        <a href="<?php echo $this->url('beheer/customers', ['action' => 'show', 'id' => $customer->getId()]); ?>" class="btn btn-danger" title="Annuleren">Annuleren</a>
    </div>  
</div>
<?php echo $this->form()->closeTag($form); ?>