
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('customer')); ?>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('surName')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formText($form->get('surName')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo (count($form->getMessages('surName')) > 0 ? $form->getMessages('surName')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('lastName')); ?>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <?php echo $this->formText($form->get('lastName')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formText($form->get('lastNamePrefix')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo (count($form->getMessages('lastName')) > 0 ? $form->getMessages('lastName')['isEmpty'] : '&nbsp;' ) ?>
        <?php echo (count($form->getMessages('lastNamePrefix')) > 0 ? $form->getMessages('lastNamePrefix')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('gender')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formRadio($form->get('gender')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo (count($form->getMessages('gender')) > 0 ? $form->getMessages('gender')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('phoneNumber')); ?>
    <div class="col-sm-6 col-md-6 col-lg-6">
        <?php echo $this->formText($form->get('phoneNumber')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo (count($form->getMessages('phoneNumber')) > 0 ? $form->getMessages('phoneNumber')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('mobilePhoneNumber')); ?>
    <div class="col-sm-6 col-md-6 col-lg-6">
        <?php echo $this->formText($form->get('mobilePhoneNumber')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo (count($form->getMessages('mobilePhoneNumber')) > 0 ? $form->getMessages('mobilePhoneNumber')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('email')); ?>
    <div class="col-sm-6 col-md-6 col-lg-6">
        <?php echo $this->formText($form->get('email')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo (count($form->getMessages('email')) > 0 ? $form->getMessages('email')['isEmpty'] : '&nbsp;' ) ?>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>