<?php
$this->headTitle('Customers');

$this->mainMenu()->setActiveItemId('customer');

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('levels.manage') => $this->url('beheer/customers'),
    $this->translator()->translate('level.edit') => $this->url('beheer/customers', ['action' => 'edit'])
]);
$form->setAttributes(array(
    'enctype' => 'multipart/form-data'
));
?>
<h1><?php echo $this->translator()->translate('manage.levels'); ?></h1>
<?php
echo $this->partial('projects/level/partials/form.phtml', array('form' => $form));
?>