<?php echo $this->form()->openTag($form); ?>
<div class="col-lg-12 col-md-12 col-sm-12">
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name')); ?>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <?php echo $this->formText($form->get('name')); ?>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <?php echo (count($form->getMessages('name')) > 0 ? $form->getMessages('name')['isEmpty'] : '&nbsp;' ) ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('shortName')); ?>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <?php echo $this->formText($form->get('shortName')); ?>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <?php echo (count($form->getMessages('shortName')) > 0 ? $form->getMessages('shortName')['isEmpty'] : '&nbsp;' ) ?>
        </div>
    </div>
    <?php
    echo $this->partial('customers/country/partials/upload_form.phtml', array('form' => $form, 'file' => $country->getFlag()));
    ?>


</div>
<div class="col-sm-12 col-md-12 col-lg-12 " style="padding-left:0;">
    <button type="submit" id="submit" class="btn btn-primary">Opslaan</button> <a href="<?php echo $this->url['beheer\countries']; ?>" class="btn btn-default" title="Annuleren">Annuleren</a>
</div>  
<?php echo $this->form()->closeTag($form); ?>