<?php
$this->headTitle('Customers');

$this->mainMenu()->setActiveItemId('customer');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    $this->translator()->translate('projects.manage') => $this->url('beheer/customers'),
]);
?>

<h1><?php echo $this->translator()->translate('projects.manage'); ?></h1>

<p>
    <a class="btn btn-primary" href="
       <?= $this->url('beheer/projects', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translator()->translate('new.project'); ?>
    </a>
    <a class="btn btn-primary" href="
       <?= $this->url('beheer/projecttypes', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translator()->translate('new.projec.type'); ?>
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th><?php echo $this->translator()->translate('table.projects.name'); ?></th>
        <th><?php echo $this->translator()->translate('table.projects.date.created'); ?></th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($projects as $project): ?>

        <tr>
            <td>
                <?= $this->escapeHtml($project->getName()); ?></a> 
            </td>
            <td><nobr></nobr></td>        
    <td>
        <a class="btn btn-dark btn-sm" href="<?= $this->url('beheer/projects', ['action' => 'edit', 'id' => $project->getId()]); ?>">
                            <i class="fas fa-edit"></i>
                        </a>
        <a class="btn btn-danger btn-sm" href="<?= $this->url('beheer/projects', ['action' => 'delete', 'id' => $project->getId()]); ?>">
                            <i class="fas fa-trash"></i>
                        </a>
    </td>    
    </tr>

<?php endforeach; ?>   

</table>
