<?php echo $this->form()->openTag($form); ?>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('surName')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formText($form->get('surName')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('surName')); ?>
    </div>
</div>
    <div class="form-group row">
        <?php echo $this->formLabel($form->get('lastName')); ?>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <?php echo $this->formText($form->get('lastName')); ?>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <?php echo $this->formElementErrors($form->get('lastName')); ?>
        </div>
    </div>
    <div class="form-group row">
        <?php echo $this->formLabel($form->get('lastNamePrefix')); ?>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <?php echo $this->formText($form->get('lastNamePrefix')); ?>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <?php echo $this->formElementErrors($form->get('lastNamePrefix')); ?>
        </div>
    </div>
    <div class="form-group row">
        <?php echo $this->formLabel($form->get('email')); ?>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <?php echo $this->formText($form->get('email')); ?>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>
    </div>
<hr />
<h2><?php echo $this->translator()->translate('manage.expertises'); ?></h2>
<?php foreach ($expertises AS $expertise) { ?>
<div class="row">
    <div class="col-md-2"><input type="checkbox" class="mr-2" name="expertise" value="<?php echo $expertise->getId(); ?>" /><?php echo $expertise->getName(); ?></div>
    <div class="col">
        <?php foreach ($levels AS $level) { ?>
                    <input type="radio" class="ml-2" name="<?php echo $expertise->getId(); ?>-expertiseLevel" value="<?php echo $expertise->getId() . '-' .  $level->getId(); ?>">
                    <?php echo $level->getName(); ?>
        <?php } ?>
    </div>
</div>
<?php } ?>

<hr />
<div class="form-group row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="submit" id="submit" class="btn btn-dark"><?php echo $this->translator()->translate('save'); ?></button>
        <a href="<?= $this->url('beheer/expertises'); ?>" class="btn btn-danger" title="<?php echo $this->translator()->translate('cancel'); ?>"><?php echo $this->translator()->translate('cancel'); ?></a>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>